name: Publish Website

on:
  push:
    branches:
     - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Repository
        uses: actions/checkout@v3

      - name: Set-up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
